
# Dependencies
markdown:         kramdown

# Permalinks
#permalink:        pretty

# Setup
title:            'Algebra and Trigonometry'
tagline:          'from http://cnx.org/contents/13ac107a-f15f-49d2-97e8-60ab2e3b519c@ (CC-BY)'
url:              https://github.com/philschatz/algebra-trigonometry-book
origin:           http://cnx.org/contents/13ac107a-f15f-49d2-97e8-60ab2e3b519c@

author:
  name:           'Openstax'
  url:            https://github.com/openstax

paginate:         5

# Custom vars
version:          

bookviewer:       https://philschatz.com/book-viewer

